# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoITV
                                 A QGIS plugin
 Ce plugin QGIS géolocalise automatiquement branchements et défauts observés lors d’iune nspection télévisée (ITV) à partir du fichier TXT normé (NF EN 13508-2+A1)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-29
        copyright            : (C) 2025 by NAOMIS
        email                : nantes@naomis.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoITV class from file GeoITV.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geo_itv import GeoITV
    return GeoITV(iface)
