# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoITVDialog
                                 A QGIS plugin
 Ce plugin QGIS géolocalise automatiquement branchements et défauts observés lors d’iune nspection télévisée (ITV) à partir du fichier TXT normé (NF EN 13508-2+A1)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-29
        git sha              : $Format:%H$
        copyright            : (C) 2025 by NAOMIS
        email                : nantes@naomis.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

from qgis.core import QgsSettings, QgsProject, QgsVectorFileWriter, QgsVectorLayer

from .utils.file_parser import FileParser
from .utils.insert_tables import insert_b01_table, insert_b02_table, insert_b03_table, insert_b04_table, insert_c_table
from .geo_itv_data import IDS
from .defect_position import DefectGeometryCalculator
USE_DB_VIEWS = False

import psycopg2
import csv

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
import os
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'geo_itv_dialog_base.ui'))


class GeoITVDialog(QtWidgets.QDialog, FORM_CLASS):
    def set_progress(self, value):
        """
        Définit la valeur de la progressBar si elle existe.
        """
        if hasattr(self, 'progressBar') and self.progressBar is not None:
            try:
                self.progressBar.setValue(value)
            except Exception:
                pass
    
    def log_info(self, message, raz=False):
        """
        Affiche un message d'information dans le widget textEdit_log s'il existe, sinon ne fait rien.
        """
        if hasattr(self, 'textEdit_log') and self.textEdit_log is not None:
            try:
                if raz:
                    self.textEdit_log.clear()
                self.textEdit_log.append(message)
            except Exception:
                pass


    def __init__(self, parent=None):
        """
        Constructeur du dialogue principal du plugin GeoITV.
        Initialise l'UI, connecte les boutons et prépare la gestion dynamique de l'état du bouton d'exécution.
        """
        super(GeoITVDialog, self).__init__(parent)
        self.setupUi(self)

        # Connexion des boutons principaux
        self.btTestConnexion.clicked.connect(self.test_connexion)
        self.btExecute.clicked.connect(self.execute)

        # État initial du bouton d'exécution
        self.update_btExecute_enabled()

        # Connexion des signaux pour activer/désactiver dynamiquement le bouton d'exécution
        if hasattr(self, 'cmbConnexionBDD'):
            self.cmbConnexionBDD.currentIndexChanged.connect(self.update_btExecute_enabled)
        if hasattr(self, 'inputFileTXT'):
            self.inputFileTXT.fileChanged.connect(self.update_btExecute_enabled)
        if hasattr(self, 'mapLayerComboBox_regard'):
            self.mapLayerComboBox_regard.layerChanged.connect(self.update_btExecute_enabled)

    def update_btExecute_enabled(self):
        """
        Active le bouton d'exécution uniquement si tous les champs obligatoires sont renseignés :
        - Connexion BDD
        - Fichier TXT
        - Couche regard
        """
        has_conn = False
        has_txt = False
        has_regard = False

        if hasattr(self, 'cmbConnexionBDD'):
            has_conn = bool(self.cmbConnexionBDD.currentText())
        if hasattr(self, 'inputFileTXT'):
            # inputFileTXT peut être un widget fichier ou un QLineEdit
            try:
                has_txt = bool(self.inputFileTXT.filePath())
            except Exception:
                has_txt = bool(self.inputFileTXT.text())
        if hasattr(self, 'mapLayerComboBox_regard'):
            try:
                has_regard = self.mapLayerComboBox_regard.currentLayer() is not None
            except Exception:
                has_regard = False

        enabled = has_conn and has_txt and has_regard
        if hasattr(self, 'btExecute'):
            self.btExecute.setEnabled(enabled)

    def get_connection_params(self, connexion_name):
        """Récupère les paramètres de connexion PostgreSQL à partir du nom de la connexion."""
        settings = QgsSettings()
        prefix = f"PostgreSQL/connections/{connexion_name}/"
        return {
            "dbname": settings.value(prefix + "database", ""),
            "user": settings.value(prefix + "username", ""),
            "password": settings.value(prefix + "password", ""),
            "host": settings.value(prefix + "host", "localhost"),
            "port": settings.value(prefix + "port", "5432"),
        }

    def test_connexion(self):
        """Test the database connection using the selected connection."""
        connexion = self.cmbConnexionBDD.currentText()
        if not connexion:
            QtWidgets.QMessageBox.warning(self, "Erreur", "Aucune connexion sélectionnée.")
            return

        connection_params = self.get_connection_params(connexion)

        try:
            conn = psycopg2.connect(
                dbname=connection_params["dbname"],
                user=connection_params["user"],
                password=connection_params["password"],
                host=connection_params["host"],
                port=connection_params["port"]
            )
            QtWidgets.QMessageBox.information(self, "Succès", f"Connexion réussie à la base '{connection_params['dbname']}' sur {connection_params['host']}:{connection_params['port']}.")
        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Erreur de connexion", f"Impossible de se connecter à la base de données : {str(e)}")
        finally:
            if 'conn' in locals() and conn:
                conn.close()

    def clear_tables(self, conn):
        """Supprime les tables du schéma 'itv' dont le nom commence par 'table_collecteur_' ou 'table_regard_'."""
        cursor = None
        try:
            cursor = conn.cursor()
            # Truncate la table inspection (et tout ce qui dépend d'elle)
            try:
                cursor.execute('TRUNCATE TABLE itv.inspection CASCADE;')
            except Exception as e:
                pass

            cursor.execute("""
                SELECT tablename FROM pg_tables
                WHERE schemaname = 'itv'
                AND (tablename LIKE 'table_collecteur_%' OR tablename LIKE 'table_regard_%')
            """)
            tables = cursor.fetchall()
            for (tablename,) in tables:
                try:
                    cursor.execute(f'DROP TABLE IF EXISTS itv."{tablename}" CASCADE;')
                except Exception as e:
                    pass
            conn.commit()
            self.log_info("Les tables temporaires ont été supprimées et la table inspection a été vidée.")
        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Erreur", f"Erreur lors de la suppression des tables : {e}")
        finally:
            if cursor is not None:
                try:
                    cursor.close()
                except Exception:
                    pass

    def import_layer_regard(self, connection_params):
        """
        Importe la couche sélectionnée dans mapLayerComboBox_regard dans la base PostgreSQL.
        """
        dbname = connection_params["dbname"]
        user = connection_params["user"]
        password = connection_params["password"]
        host = connection_params["host"]
        port = connection_params["port"]

        # 1. Récupérer la couche sélectionnée
        layer = self.mapLayerComboBox_regard.currentLayer()
        if not layer:
            QtWidgets.QMessageBox.warning(self, "Erreur", "Aucune couche regard sélectionnée.")
            return

        # 2. Définir le nom de la table cible
        formatted_table_name = f"table_regard_{layer.name().replace(' ', '_').replace('-', '_').lower()}"
        if len(formatted_table_name) > 60:
            formatted_table_name = formatted_table_name[:60]

        # 3. Nettoyer les champs texte pour garantir l'encodage UTF-8 strict (remplacement des caractères non-ASCII)
        import re
        layer.startEditing()
        for feature in layer.getFeatures():
            attrs = feature.attributes()
            for idx, field in enumerate(layer.fields()):
                val = attrs[idx]
                if field.typeName().lower() in ['string', 'text'] and val is not None:
                    try:
                        if isinstance(val, bytes):
                            val_str = val.decode('utf-8', errors='replace')
                        else:
                            val_str = str(val)
                        # Remplacer tout caractère non-ASCII par un espace
                        val_clean = re.sub(r'[^\x20-\x7E]', ' ', val_str)
                        if val != val_clean:
                            layer.changeAttributeValue(feature.id(), idx, val_clean)
                    except Exception:
                        layer.changeAttributeValue(feature.id(), idx, "")
        layer.commitChanges()

        # 4. Ecrire la couche temporaire dans PostgreSQL
        uri = f"PG:host={host} port={port} dbname={dbname} user={user} password={password}"
        options = QgsVectorFileWriter.SaveVectorOptions()
        options.driverName = "PostgreSQL"
        options.layerName = formatted_table_name
        options.actionOnExistingFile = QgsVectorFileWriter.CreateOrOverwriteLayer
        options.layerOptions = [
            "GEOMETRY_NAME=geom",
            "SCHEMA=itv",
            "OVERWRITE=YES",
            "precision=NO"
        ]

        try:
            error, error_string = QgsVectorFileWriter.writeAsVectorFormatV2(
                layer,
                uri,
                QgsProject.instance().transformContext(),
                options
            )
            if error == QgsVectorFileWriter.NoError:
                self.log_info(f"Couche 'regard' importée dans itv.{formatted_table_name}")
            else:
                QtWidgets.QMessageBox.critical(self, "Erreur", f"Erreur lors de l'import : {error_string}")
        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Erreur", f"Erreur inattendue lors de l'export : {str(e)}")
    
    def import_layer_collecteur(self, connection_params):
        """
        Importe la couche sélectionnée dans mapLayerComboBox_collecteur dans la base PostgreSQL.
        """
        dbname = connection_params["dbname"]
        user = connection_params["user"]
        password = connection_params["password"]
        host = connection_params["host"]
        port = connection_params["port"]

        # 1. Récupérer la couche sélectionnée
        layer = self.mapLayerComboBox_collecteur.currentLayer()
        if not layer:
            self.log_info("Aucune couche 'collecteur'sélectionnée.")
            return

        # 2. Définir le nom de la table cible
        formatted_table_name = f"table_collecteur_{layer.name().replace(' ', '_').replace('-', '_').lower()}"
        if len(formatted_table_name) > 60:
            formatted_table_name = formatted_table_name[:60]

        # 3. Nettoyer les champs texte pour garantir l'encodage UTF-8 strict (remplacement des caractères non-ASCII)
        import re
        layer.startEditing()
        for feature in layer.getFeatures():
            attrs = feature.attributes()
            for idx, field in enumerate(layer.fields()):
                val = attrs[idx]
                if field.typeName().lower() in ['string', 'text'] and val is not None:
                    try:
                        if isinstance(val, bytes):
                            val_str = val.decode('utf-8', errors='replace')
                        else:
                            val_str = str(val)
                        # Remplacer tout caractère non-ASCII par un espace
                        val_clean = re.sub(r'[^\x20-\x7E]', ' ', val_str)
                        if val != val_clean:
                            layer.changeAttributeValue(feature.id(), idx, val_clean)
                    except Exception:
                        layer.changeAttributeValue(feature.id(), idx, "")
        layer.commitChanges()

        # 4. Ecrire la couche temporaire dans PostgreSQL
        uri = f"PG:host={host} port={port} dbname={dbname} user={user} password={password}"
        options = QgsVectorFileWriter.SaveVectorOptions()
        options.driverName = "PostgreSQL"
        options.layerName = formatted_table_name
        options.actionOnExistingFile = QgsVectorFileWriter.CreateOrOverwriteLayer
        options.layerOptions = [
            "GEOMETRY_NAME=geom",
            "SCHEMA=itv",
            "OVERWRITE=YES",
            "precision=NO"
        ]

        try:
            error, error_string = QgsVectorFileWriter.writeAsVectorFormatV2(
                layer,
                uri,
                QgsProject.instance().transformContext(),
                options
            )
            if error == QgsVectorFileWriter.NoError:
                self.log_info(f"Couche 'collecteur'importée dans itv.{formatted_table_name}")
            else:
                QtWidgets.QMessageBox.critical(self, "Erreur", f"Erreur lors de l'import : {error_string}")
        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Erreur", f"Erreur inattendue lors de l'export : {str(e)}")

    def insert_metadata(self, conn, file_path, metadata):
        """
        Insère les métadonnées dans la table `itv.inspection` en utilisant la connexion configurée et les nouveaux widgets.
        """
        cursor = None
        try:
            cursor = conn.cursor()
            # Requête SQL pour insérer les métadonnées
            query = """
                INSERT INTO itv.inspection (
                    gid, file, "A1", "A2", "A3", "A4", "A5", "A6", shp_reg, shp_coll,
                    entreprise, pdf_filename, shp_reg_table, shp_coll_table, shp_reg_id_fieldname, shp_coll_id_fieldname, created_by
                ) VALUES (DEFAULT, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING gid;
            """

            # Récupérer les noms des couches sélectionnées (collecteur et regard)
            layer_collecteur = self.mapLayerComboBox_collecteur.currentLayer() if hasattr(self, 'mapLayerComboBox_collecteur') else None
            layer_regard = self.mapLayerComboBox_regard.currentLayer() if hasattr(self, 'mapLayerComboBox_regard') else None
            shp_coll = layer_collecteur.name() if layer_collecteur else None
            shp_reg = layer_regard.name() if layer_regard else None

            # Nom de la table regard (optionnelle)
            if layer_regard:
                table_name_reg = layer_regard.name()
                shp_reg_table = f"table_regard_{table_name_reg}".replace(" ", "_").replace("-", "_").lower()
                if len(shp_reg_table) > 60:
                    shp_reg_table = shp_reg_table[:60]
            else:
                shp_reg_table = None

            # Nom de la table collecteur (optionnelle)
            if layer_collecteur:
                table_name_coll = layer_collecteur.name()
                shp_coll_table = f"table_collecteur_{table_name_coll}".replace(" ", "_").replace("-", "_").lower()
                if len(shp_coll_table) > 60:
                    shp_coll_table = shp_coll_table[:60]
            else:
                shp_coll_table = None

            # PDF et entreprise
            pdf_filename = self.lineEdit_rapport.text() if hasattr(self, 'lineEdit_rapport') else None
            enterprise_name = self.lineEdit_entreprise.text() if hasattr(self, 'lineEdit_entreprise') else None

            # Champs de jointure
            shp_reg_id_fieldname = self.fieldComboBox_regard.currentText() if hasattr(self, 'fieldComboBox_regard') and self.fieldComboBox_regard.currentIndex() != -1 else None
            shp_coll_id_fieldname = self.fieldComboBox_collecteur.currentText() if hasattr(self, 'fieldComboBox_collecteur') and self.fieldComboBox_collecteur.currentIndex() != -1 else None
            
            # Préparation des valeurs à insérer
            values = (
                file_path,  # Nom du fichier
                metadata.get("charset"),  # A1
                metadata.get("language"),  # A2
                metadata.get("delimiter"),  # A3
                metadata.get("decimalSeparator"),  # A4
                metadata.get("quoteChar"),  # A5
                metadata.get("version"),  # A6
                shp_reg,  # Nom de la couche regard
                shp_coll,  # Nom de la couche collecteur
                enterprise_name,  # Nom de l'entreprise
                pdf_filename,  # Nom du fichier PDF
                shp_reg_table,  # Nom de la table shp_reg
                shp_coll_table,  # Nom de la table shp_coll
                shp_reg_id_fieldname,  # Champ jointure regard
                shp_coll_id_fieldname,  # Champ jointure collecteur
                1  # created_by (exemple)
            )

            # Exécution de la requête
            cursor.execute(query, values)
            inspection_gid = cursor.fetchone()[0]  # Récupère l'ID généré

            # Validation des changements
            conn.commit()
            self.log_info(f"Métadonnées insérées avec succès dans la table `inspection` avec gid={inspection_gid}.")

            return inspection_gid

        except psycopg2.OperationalError as e:
            QtWidgets.QMessageBox.critical(self, "Erreur de connexion", f"Erreur de connexion : {str(e)}")
        except psycopg2.Error as e:
            QtWidgets.QMessageBox.critical(self, "Erreur SQL", f"Erreur SQL : {str(e)}")
        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Erreur inattendue", f"Erreur inattendue : {str(e)}")
        finally:
            if cursor is not None:
                try:
                    cursor.close()
                except Exception:
                    pass
        return None

    def insert_data(self, conn, inspection_gid, passages):
        """
        Insère les passages dans la table `itv.passage` pour une inspection donnée, ainsi que les tables associées, en utilisant la connexion configurée.
        Affiche le numéro de passage dans le log.
        """
        cursor = None
        total = len(passages)

        try:
            cursor = conn.cursor()
            query = """
                INSERT INTO itv.passage (
                    gid, n_passage, inspection_gid
                ) VALUES (DEFAULT, %s, %s)
                RETURNING gid;
            """

            for idx, passage in enumerate(passages, 1):
                n_passage = passage.get("n_passage")
                self.log_info(f"Insertion du passage n°{n_passage} ({idx}/{total})... !")
                cursor.execute(query, (n_passage, inspection_gid))
                passage_gid = cursor.fetchone()[0]

                # Insérer les données des tables associées au passage si elles existent
                if "tables" in passage:
                    if "#B01" in passage["tables"]:
                        b01_data = passage["tables"]["#B01"]
                        insert_b01_table(self, cursor, passage_gid, b01_data)
                    if "#B02" in passage["tables"]:
                        b02_data = passage["tables"]["#B02"]
                        insert_b02_table(self, cursor, passage_gid, b02_data)
                    if "#B03" in passage["tables"]:
                        b03_data = passage["tables"]["#B03"]
                        insert_b03_table(self, cursor, passage_gid, b03_data)
                    if "#B04" in passage["tables"]:
                        b04_data = passage["tables"]["#B04"]
                        insert_b04_table(self, cursor, passage_gid, b04_data)
                    if "#C" in passage["tables"]:
                        c_data = passage["tables"]["#C"]
                        insert_c_table(self, cursor, passage_gid, c_data)

            conn.commit()
            self.log_info("Passages insérés avec succès dans la table `passage` et les tables associées.")

        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Erreur", f"Erreur lors de l'insertion des passages : {str(e)}")
        finally:
            if cursor is not None:
                try:
                    cursor.close()
                except Exception:
                    pass
    def import_txt_data(self, conn):
        """
        Charge les données extraites du fichier TXT dans la base de données.
        Retourne TOUJOURS (inspection_gid, details), même en cas d'erreur.
        """
        file_path = self.inputFileTXT.filePath()
        if not file_path:
            QtWidgets.QMessageBox.critical(self, "Erreur", "Veuillez sélectionner un fichier TXT avant de continuer.")
            return None, [] 

        inspection_gid = None
        details = []  

        try:
            parser = FileParser()
            parsed_data = parser.parse(file_path)

            metadata = parsed_data.get("metadata", {})
            passages = parsed_data.get("passages", [])
            details = parsed_data.get("details", [])  

            inspection_gid = self.insert_metadata(conn, file_path, metadata)
            if inspection_gid:
                self.insert_data(conn, inspection_gid, passages)
                self.log_info("Processus d'importation terminé avec succès.")
            else:
                QtWidgets.QMessageBox.critical(
                    self,
                    "Erreur",
                    "Erreur lors de l'insertion des métadonnées. Processus interrompu."
                )
                details = []  

        except Exception as e:
            QtWidgets.QMessageBox.critical(
                self,
                "Erreur",
                f"Erreur lors de l'importation des données : {str(e)}"
            )
            details = []  

        return inspection_gid, details  
    
    def set_id_sig(self, conn, inspection_gid):
        """
        Exécute la fonction SQL `itv.set_id_sig` sur la base de données et affiche un message de succès.
        """
        cursor = None
        try:
            cursor = conn.cursor()
            query = f"SELECT itv.set_id_sig({inspection_gid})"
            cursor.execute(query)
            conn.commit()
            self.log_info("Mise à jour des correspondances effectuée avec succès.")
        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Erreur", f"Erreur lors de l'exécution de la fonction SQL : {str(e)}")
        finally:
            if cursor is not None:
                try:
                    cursor.close()
                except Exception:
                    pass
    
    def update_ids_reg_from_csv(self, conn, inspection_gid):
        """
        Met à jour la colonne id_sig dans itv.ids_reg à partir d'un CSV si fichier de correspondance regard fourni.
        """
        csv_path = self.inputFileCSV_regard.filePath()
        if not csv_path or not os.path.exists(csv_path):
            self.log_info("Aucun fichier CSV de correspondance regard accessible. Opération ignorée.")
            return []

        cursor = None
        try:
            correspondance_data = {}

            with open(csv_path, "r", encoding="utf-8-sig") as f:
                first_line = f.readline()

                if "\t" in first_line and "," not in first_line and ";" not in first_line:
                    sep = "\t"
                elif ";" in first_line and "," not in first_line:
                    sep = ";"
                else:
                    sep = ","

                headers = [h.strip() for h in first_line.strip().split(sep)]

                if "id_itv" not in headers or "id_sig" not in headers:
                    raise ValueError("Le CSV doit contenir les colonnes 'id_itv' et 'id_sig'.")

                id_itv_index = headers.index("id_itv")
                id_sig_index = headers.index("id_sig")

                for line in f:
                    if not line.strip():
                        continue

                    values = [v.strip() for v in line.strip().split(sep)]
                    if len(values) <= max(id_itv_index, id_sig_index):
                        continue

                    id_itv = values[id_itv_index].strip('"')
                    id_sig = values[id_sig_index].strip('"')

                    if id_itv and id_sig:
                        correspondance_data[id_itv] = id_sig

            cursor = conn.cursor()

            for id_itv, id_sig in correspondance_data.items():
                update_query = """
                    UPDATE itv.ids_reg
                    SET id_sig = %s
                    WHERE inspection_gid = %s
                    AND id_itv = %s
                """
                cursor.execute(update_query, (id_sig, inspection_gid, id_itv))

            conn.commit()
            self.log_info(f"Correspondances regard mises à jour avec succès ({len(correspondance_data)} lignes).")
            return correspondance_data

        except Exception as e:
            QtWidgets.QMessageBox.critical(
                self,
                "Erreur",
                f"Erreur lors de la mise à jour de la table itv.ids_reg : {str(e)}"
            )
            return []

        finally:
            if cursor is not None:
                try:
                    cursor.close()
                except Exception:
                    pass    
                
    def update_ids_coll_from_csv(self, conn, inspection_gid):
        """
        Met à jour la colonne id_sig dans itv.ids_coll à partir d'un CSV si fichier de correspondance collecteur fourni.
        """
        csv_path = self.inputFileCSV_collecteur.filePath()
        if not csv_path or not os.path.exists(csv_path):
            self.log_info("Aucun fichier CSV de correspondance collecteur accessible. Opération ignorée.")
            return

        cursor = None
        try:
            correspondance_data = {}
            with open(csv_path, "r", encoding="utf-8") as f:
                first_line = f.readline()
                if "\t" in first_line and "," not in first_line and ";" not in first_line:
                    sep = "\t"
                elif ";" in first_line and "," not in first_line:
                    sep = ";"
                else:
                    sep = ","
                headers = [h.strip() for h in first_line.strip().split(sep)]

                id_troncon_col = "id_troncon" if "id_troncon" in headers else ("id_itv" if "id_itv" in headers else None)
                if not id_troncon_col or "id_sig" not in headers:
                    QtWidgets.QMessageBox.critical(self, "Erreur", "Le CSV doit contenir 'id_troncon' ou 'id_itv' et 'id_sig'.")
                    return

                id_troncon_index = headers.index(id_troncon_col)
                id_sig_index = headers.index("id_sig")

                for line in f:
                    if not line.strip():
                        continue
                    values = [v.strip() for v in line.strip().split(sep)]
                    if len(values) <= max(id_troncon_index, id_sig_index):
                        continue
                    id_troncon = values[id_troncon_index]
                    id_sig = values[id_sig_index] if id_sig_index < len(values) else None
                    if id_troncon and id_sig:
                        correspondance_data[id_troncon] = id_sig

            cursor = conn.cursor()

            for id_troncon, id_sig in correspondance_data.items():
                update_query = """
                    UPDATE itv.ids_coll
                    SET id_sig = %s
                    WHERE id_sig IS NULL AND inspection_gid = %s AND id_itv = %s
                """
                cursor.execute(update_query, (id_sig, inspection_gid, id_troncon))
            conn.commit()
            self.log_info("Correspondances collecteur mises à jour avec succès.")
        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Erreur", f"Erreur lors de la mise à jour de la table itv.ids_coll : {str(e)}")
        finally:
            if cursor is not None:
                try:
                    cursor.close()
                except Exception:
                    pass
                
    def display_v_inspection_view(self, connection_params, inspection_gid):
        """
        Affiche dans QGIS la vue SQL `itv.v_inspection` pour une inspection donnée et zoome sur l'emprise de la couche.
        """
        try:

            dbname = connection_params["dbname"]
            user = connection_params["user"]
            password = connection_params["password"]
            host = connection_params["host"]
            port = connection_params["port"]

            query = f"(SELECT * FROM itv.v_inspection WHERE inspection_gid = {inspection_gid})"
            geom_column = "geom"
            primary_key = "inspection_gid"

            uri = (
                f"dbname='{dbname}' host={host} port={port} user='{user}' password='{password}' "
                f"key='{primary_key}' type=Polygon table=\"({query})\" ({geom_column})"
            )

            layer_name = f"itv_inspection-{inspection_gid}"
            layer = QgsVectorLayer(uri, layer_name, "postgres")
            if layer.isValid():
                QgsProject.instance().addMapLayer(layer)
                # Appliquer un style QML natif PyQGIS si le fichier existe
                try:
                    qml_path = os.path.join(os.path.dirname(__file__), 'styles', 'itv_inspection.qml')
                    if os.path.exists(qml_path):
                        layer.loadNamedStyle(qml_path)
                        layer.triggerRepaint()
                except Exception as e:
                    self.log_info(f"Impossible d'appliquer le style QML : {e}")
                # Zoom sur l'emprise
                iface = self.iface if hasattr(self, 'iface') else None
                if iface:
                    canvas = iface.mapCanvas()
                    canvas.setExtent(layer.extent())
                    canvas.refresh()
            else:
                QtWidgets.QMessageBox.critical(self, "Erreur", f"Impossible de charger la vue 'itv.v_inspection' pour l'inspection {inspection_gid} dans QGIS.")
        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Erreur", f"Erreur inattendue lors de l'affichage de la vue : {str(e)}")

    def display_v_itv_details_geom_view(self, connection_params, inspection_gid):
        """
        Affiche dans QGIS la vue SQL `itv.v_itv_details_geom` pour une inspection donnée.
        """
        try:

            dbname = connection_params["dbname"]
            user = connection_params["user"]
            password = connection_params["password"]
            host = connection_params["host"]
            port = connection_params["port"]

            query = f"(SELECT * FROM itv.v_itv_details_geom WHERE inspection_gid = {inspection_gid})"
            geom_column = "geom"
            primary_key = "gid"

            uri = (
                f"dbname='{dbname}' host={host} port={port} user='{user}' password='{password}' "
                f"key='{primary_key}' type=Point table=\"({query})\" ({geom_column})"
            )

            layer_name = f"itv_details-{inspection_gid}"
            layer = QgsVectorLayer(uri, layer_name, "postgres")
            if layer.isValid():
                QgsProject.instance().addMapLayer(layer)
                # Appliquer un style QML natif PyQGIS si le fichier existe
                try:
                    qml_path = os.path.join(os.path.dirname(__file__), 'styles', 'itv_details_geom.qml')
                    if os.path.exists(qml_path):
                        layer.loadNamedStyle(qml_path)
                        layer.triggerRepaint()
                except Exception as e:
                    self.log_info(f"Impossible d'appliquer le style QML : {e}")
            else:
                QtWidgets.QMessageBox.critical(self, "Erreur", f"Impossible de charger la vue 'itv.v_itv_details_geom' pour l'inspection {inspection_gid} dans QGIS.")

        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Erreur", f"Erreur inattendue lors de l'affichage de la vue : {str(e)}")

    def display_v_itv_details_bcht_view(self, connection_params, inspection_gid):
        """
        Affiche dans QGIS la vue SQL `itv.v_itv_details_bcht` pour une inspection donnée.
        Importe également la vue `itv.v_itv_details_bcht_lines` si elle existe.
        """
        try:

            dbname = connection_params["dbname"]
            user = connection_params["user"]
            password = connection_params["password"]
            host = connection_params["host"]
            port = connection_params["port"]

            # Vue points
            query = f"(SELECT * FROM itv.v_itv_details_bcht WHERE inspection_gid = {inspection_gid})"
            geom_column = "geom"
            primary_key = "id"
            uri = (
                f"dbname='{dbname}' host={host} port={port} user='{user}' password='{password}' "
                f"key='{primary_key}' type=Point table=\"({query})\" ({geom_column})"
            )
            layer_name = f"itv_details_bcht-{inspection_gid}"
            layer = QgsVectorLayer(uri, layer_name, "postgres")
            if layer.isValid():
                QgsProject.instance().addMapLayer(layer)
                # Appliquer un style QML natif PyQGIS si le fichier existe
                try:
                    qml_path = os.path.join(os.path.dirname(__file__), 'styles', 'itv_details_bcht.qml')
                    if os.path.exists(qml_path):
                        layer.loadNamedStyle(qml_path)
                        layer.triggerRepaint()
                except Exception as e:
                    self.log_info(f"Impossible d'appliquer le style QML : {e}")
            else:
                QtWidgets.QMessageBox.critical(self, "Erreur", f"Impossible de charger la vue 'itv.v_itv_details_bcht' pour l'inspection {inspection_gid} dans QGIS.")

            # Vue lines (orientation)
            sql_query_lines = f"(SELECT * FROM itv.v_itv_details_bcht_lines WHERE inspection_gid = {inspection_gid})"
            geom_column_lines = "geom"
            primary_key_lines = "id"
            uri_lines = (
                f"dbname='{dbname}' host={host} port={port} user='{user}' password='{password}' "
                f"key='{primary_key_lines}' type=LineString table=\"({sql_query_lines})\" ({geom_column_lines})"
            )
            layer_name_lines = f"itv_details_bcht_lines-{inspection_gid}"
            layer_lines = QgsVectorLayer(uri_lines, layer_name_lines, "postgres")
            if layer_lines.isValid():
                QgsProject.instance().addMapLayer(layer_lines)
                # Appliquer un style QML natif PyQGIS si le fichier existe
                try:
                    qml_path = os.path.join(os.path.dirname(__file__), 'styles', 'itv_details_bcht_lines.qml')
                    if os.path.exists(qml_path):
                        result, error_msg = layer_lines.loadNamedStyle(qml_path)
                        layer_lines.triggerRepaint()
                except Exception as e:
                    self.log_info(f"Impossible d'appliquer le style QML : {e}")

        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Erreur", f"Erreur inattendue lors de l'affichage de la vue : {str(e)}")
    
    def load_ids_tables(self, connection_params, inspection_gid):
        """
        Charge les tables `ids_coll` et `ids_reg` dans QGIS pour une inspection donnée (sans géométrie, comme des tables CSV).
        Affiche également les données dans les logs/messages.
        """
        try:

            dbname = connection_params["dbname"]
            user = connection_params["user"]
            password = connection_params["password"]
            host = connection_params["host"]
            port = connection_params["port"]

            # ids_reg
            query_reg = f"(SELECT * FROM itv.v_itv_physiq_reg WHERE inspection_gid = {inspection_gid})"
            uri_reg = (
                f"dbname='{dbname}' host={host} port={port} user='{user}' password='{password}' "
                f"key='gid' type=NONE table=\"{query_reg}\""
            )
            layer_reg = QgsVectorLayer(uri_reg, f"ids_reg - Inspection {inspection_gid}", "postgres")
            if layer_reg.isValid() and layer_reg.featureCount() > 0:
                QgsProject.instance().addMapLayer(layer_reg)
                self.log_info(f"Table 'v_itv_physiq_reg' pour l'inspection {inspection_gid} ajoutée à QGIS. ({layer_reg.featureCount()} lignes, champs: {[f.name() for f in layer_reg.fields()]})")
            else:
                self.log_info(f"Aucune donnée trouvée ou impossible de charger 'v_itv_physiq_reg' pour inspection_gid={inspection_gid}. (Champs: {[f.name() for f in layer_reg.fields()]})")

            # ids_coll
            query_coll = f"(SELECT * FROM itv.v_itv_physiq_coll WHERE inspection_gid = {inspection_gid})"
            uri_coll = (
                f"dbname='{dbname}' host={host} port={port} user='{user}' password='{password}' "
                f"key='gid' type=NONE table=\"{query_coll}\""
            )
            layer_coll = QgsVectorLayer(uri_coll, f"ids_coll - Inspection {inspection_gid}", "postgres")
            if layer_coll.isValid() and layer_coll.featureCount() > 0:
                QgsProject.instance().addMapLayer(layer_coll)
                self.log_info(f"Table 'v_itv_physiq_coll' pour l'inspection {inspection_gid} ajoutée à QGIS. ({layer_coll.featureCount()} lignes, champs: {[f.name() for f in layer_coll.fields()]})")
            else:
                self.log_info(f"Aucune donnée trouvée ou impossible de charger 'v_itv_physiq_coll' pour inspection_gid={inspection_gid}. (Champs: {[f.name() for f in layer_coll.fields()]})")

        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "Erreur", f"Erreur inattendue lors du chargement des tables : {str(e)}")
        finally:
            pass

    def calculate_and_show_defect_positions(self):
        """Calcule et ajoute la couche des défauts au projet à partir de `self.details`."""
        try:
            if not hasattr(self, 'details') or not self.details:
                self.log_info("Aucune donnée ITV chargée (details manquants) : pas de calcul des positions des défauts.")
                return

            layer_regard = self.mapLayerComboBox_regard.currentLayer() if hasattr(self, 'mapLayerComboBox_regard') else None

            if not layer_regard:
                self.log_info("Couche regard non sélectionnée : impossibilité de calculer les défauts.")
                return

            layer_collecteur = self.mapLayerComboBox_collecteur.currentLayer() if hasattr(self, 'mapLayerComboBox_collecteur') else None

            self.log_info("Calcul des positions des défauts...")

            defects_list = []
            for detail in self.details:
                if not hasattr(detail, 'defauts') or not detail.defauts:
                    continue
                for d in detail.defauts:
                    defect = {
                        'gid': getattr(d, 'gid', None) or 0,
                        'code_obs': getattr(d, 'code_obs', None) or '',
                        'libel_obs': getattr(d, 'libel_obs', None) or '',
                        'metrage': getattr(d, 'metrage', None),
                        'id_reg_ent': getattr(d, 'id_reg_ent', None),
                        'id_reg_sor': getattr(d, 'id_reg_sor', None),
                        'id_troncon': getattr(d, 'id_troncon', None),
                    }
                    defects_list.append(defect)

            if not defects_list:
                self.log_info("Aucun défaut à géolocaliser.")
                return

            calc = DefectGeometryCalculator(iface=getattr(self, 'iface', None))

            layer_defauts = calc.get_defect_positions(
                defects_list,
                layer_regard,
                layer_collecteur,  
                id_field_regard=(self.fieldComboBox_regard.currentText() if hasattr(self, 'fieldComboBox_regard') else 'id'),
                id_field_collecteur=(self.fieldComboBox_collecteur.currentText() if hasattr(self, 'fieldComboBox_collecteur') else 'id')
            )

            if layer_defauts and layer_defauts.isValid():
                QgsProject.instance().addMapLayer(layer_defauts)
                self.log_info("Couche des défauts ajoutée au projet.")
            else:
                self.log_info("Impossible de générer la couche des défauts.")

        except Exception as e:
            self.log_info(f"Erreur lors du calcul/affichage des défauts : {e}")
        
    
    def execute(self):
        """
        Lance le traitement principal :
        - Vérifie la sélection de la base
        - Effectue chaque étape du workflow (suppression, import, calculs, affichage)
        - Met à jour la progressBar à chaque étape clé
        - Logue les étapes dans le textEdit_log
        """
        connexion = self.cmbConnexionBDD.currentText()
        if not connexion:
            QtWidgets.QMessageBox.warning(self, "Erreur", "Aucune connexion sélectionnée.")
            return

        # Connexion à PostgreSQL
        connection_params = self.get_connection_params(connexion)
        try:
            conn = psycopg2.connect(
                dbname=connection_params["dbname"],
                user=connection_params["user"],
                password=connection_params["password"],
                host=connection_params["host"],
                port=connection_params["port"]
            )
        except Exception as e:
            QtWidgets.QMessageBox.critical(
                self,
                "Erreur de connexion",
                f"Impossible de se connecter à la base de données : {str(e)}"
            )
            return

        error_happened = False
        details = []
        inspection_gid = None

        try:
            self.set_progress(0)
            self.log_info("Début du traitement GeoITV.", True)

            self.log_info("Suppression des tables temporaires et vidage de la table inspection...")
            self.clear_tables(conn)
            self.set_progress(10)

            self.log_info("Import de la couche regard...")
            self.import_layer_regard(connection_params)
            self.set_progress(20)

            self.log_info("Import de la couche collecteur...")
            self.import_layer_collecteur(connection_params)
            self.set_progress(30)

            self.log_info("Import des données du fichier TXT ITV...")
            inspection_gid, details = self.import_txt_data(conn)

            if inspection_gid is None:
                QtWidgets.QMessageBox.critical(
                    self,
                    "Erreur",
                    "Impossible de récupérer l'ID de l'inspection. Vérifiez les données du fichier TXT."
                )
                error_happened = True
                return

            self.inspection_gid = inspection_gid
            self.details = details
            self.set_progress(50)

            self.log_info("Affectation des identifiants SIG...")
            self.set_id_sig(conn, inspection_gid)
            self.set_progress(60)

            self.log_info("Mise à jour des correspondances regard (si CSV fourni)...")
            self.update_ids_reg_from_csv(conn, inspection_gid)
            self.set_progress(70)

            self.log_info("Mise à jour des correspondances collecteur (si CSV fourni)...")
            self.update_ids_coll_from_csv(conn, inspection_gid)
            self.set_progress(75)

            self.log_info("Affichage des résultats (couches et tables)...")
            if USE_DB_VIEWS:
                self.display_v_inspection_view(connection_params, inspection_gid)
                self.set_progress(80)
                self.display_v_itv_details_geom_view(connection_params, inspection_gid)
                self.set_progress(85)
                self.display_v_itv_details_bcht_view(connection_params, inspection_gid)
                self.set_progress(90)
            else:
                self.log_info("Chargement des vues SQL désactivé (USE_DB_VIEWS=False) — saut des affichages SQL.")
                self.set_progress(90)

            self.calculate_and_show_defect_positions()
            self.load_ids_tables(connection_params, inspection_gid)
            self.set_progress(100)

        except Exception as e:
            error_happened = True
            self.log_info(f"Erreur lors du traitement : {e}")
            QtWidgets.QMessageBox.critical(self, "Erreur", f"Erreur inattendue lors du traitement : {e}")
        finally:
            if conn is not None:
                try:
                    conn.close()
                except Exception:
                    pass
            if error_happened:
                self.log_info("Traitement terminé avec erreurs.")
            else:
                self.log_info("Traitement terminé avec succès.")